import { useEffect } from 'react';

// 100 Usuarios reales de Chile con direcciones específicas
const demoUsers = [
  // === 30 USUARIOS EN CHAMISERO, COLINA ===
  { id: 1, name: 'Carlos Mendoza Silva', username: 'carlosmendoza', email: 'carlos.mendoza@gmail.com', avatar: 'https://i.pravatar.cc/100?img=11', following: 28, likes: 0, followers: 45, verified: true, neighborhood: 'Chamisero', bio: 'Ingeniero civil.', address: 'Avenida Chamisero 10460', addressNumber: '10460', addressStreet: 'Avenida Chamisero', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2000, longitude: -70.6500 },
  { id: 2, name: 'Maria Elena Rodriguez', username: 'mariaelena', email: 'maria.elena@outlook.com', avatar: 'https://i.pravatar.cc/100?img=5', following: 35, likes: 124, followers: 52, verified: true, neighborhood: 'Chamisero', bio: 'Profesora historia.', address: 'Avenida Chamisero 10500', addressNumber: '10500', addressStreet: 'Avenida Chamisero', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2010, longitude: -70.6510 },
  { id: 3, name: 'Juan Pablo Torres', username: 'jptorres', email: 'juan.torres@gmail.com', avatar: 'https://i.pravatar.cc/100?img=12', following: 19, likes: 67, followers: 23, verified: false, neighborhood: 'Chamisero', bio: 'Arquitecto.', address: 'Avenida Chamisero 10550', addressNumber: '10550', addressStreet: 'Avenida Chamisero', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2020, longitude: -70.6520 },
  { id: 4, name: 'Ana Maria Fernandez', username: 'anafernandez', email: 'ana.fernandez@gmail.com', avatar: 'https://i.pravatar.cc/100?img=9', following: 41, likes: 178, followers: 61, verified: true, neighborhood: 'Chamisero', bio: 'Medico general.', address: 'Camino Los Cerezos 150', addressNumber: '150', addressStreet: 'Camino Los Cerezos', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2030, longitude: -70.6530 },
  { id: 5, name: 'Josephin Water', username: 'josephinwater', email: 'josephin.water@gmail.com', avatar: 'https://i.pravatar.cc/100?img=8', following: 42, likes: 156, followers: 38, verified: true, neighborhood: 'Chamisero', bio: 'Diseñadora UX.', address: 'Avenida Chamisero 10460', addressNumber: '10460', addressStreet: 'Avenida Chamisero', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2000, longitude: -70.6500 },
  { id: 6, name: 'Roberto Carlos Gomez', username: 'rgomez', email: 'roberto.gomez@gmail.com', avatar: 'https://i.pravatar.cc/100?img=13', following: 678, likes: 12345, followers: 2890, verified: true, neighborhood: 'Chamisero', bio: 'Abogado.', address: 'Calle Los Aromos 200', addressNumber: '200', addressStreet: 'Calle Los Aromos', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2040, longitude: -70.6540 },
  { id: 7, name: 'Patricia Vasquez Lopez', username: 'patyvasquez', email: 'patricia.vasquez@gmail.com', avatar: 'https://i.pravatar.cc/100?img=10', following: 345, likes: 5678, followers: 1234, verified: false, neighborhood: 'Chamisero', bio: 'Lider comunitaria.', address: 'Camino Los Maitenes 250', addressNumber: '250', addressStreet: 'Camino Los Maitenes', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2050, longitude: -70.6550 },
  { id: 8, name: 'Miguel Angel Santos', username: 'miguelsantos', email: 'miguel.santos@gmail.com', avatar: 'https://i.pravatar.cc/100?img=14', following: 543, likes: 9876, followers: 2156, verified: true, neighborhood: 'Chamisero', bio: 'Contador.', address: 'Avenida Chamisero 10600', addressNumber: '10600', addressStreet: 'Avenida Chamisero', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2060, longitude: -70.6560 },
  { id: 9, name: 'Carmen Gloria Rojas', username: 'carmenrojas', email: 'carmen.rojas@gmail.com', avatar: 'https://i.pravatar.cc/100?img=15', following: 234, likes: 4567, followers: 987, verified: false, neighborhood: 'Chamisero', bio: 'Enfermera.', address: 'Avenida Chamisero 10650', addressNumber: '10650', addressStreet: 'Avenida Chamisero', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2070, longitude: -70.6570 },
  { id: 10, name: 'Francisco Javier Diaz', username: 'franciscodiaz', email: 'francisco.diaz@gmail.com', avatar: 'https://i.pravatar.cc/100?img=16', following: 876, likes: 15678, followers: 3456, verified: true, neighborhood: 'Chamisero', bio: 'Empresario.', address: 'Calle Los Cerezos 300', addressNumber: '300', addressStreet: 'Calle Los Cerezos', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2080, longitude: -70.6580 },
  { id: 11, name: 'Rosa Maria Herrera', username: 'rosaherrera', email: 'rosa.herrera@gmail.com', avatar: 'https://i.pravatar.cc/100?img=17', following: 123, likes: 2345, followers: 567, verified: false, neighborhood: 'Chamisero', bio: 'Artesana.', address: 'Calle Los Aromos 350', addressNumber: '350', addressStreet: 'Calle Los Aromos', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2090, longitude: -70.6590 },
  { id: 12, name: 'Luis Alberto Munoz', username: 'luismunoz', email: 'luis.munoz@gmail.com', avatar: 'https://i.pravatar.cc/100?img=18', following: 654, likes: 11234, followers: 2789, verified: true, neighborhood: 'Chamisero', bio: 'Musico.', address: 'Camino Los Maitenes 400', addressNumber: '400', addressStreet: 'Camino Los Maitenes', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2100, longitude: -70.6600 },
  { id: 13, name: 'Isabel Margarita Flores', username: 'isabelflores', email: 'isabel.flores@gmail.com', avatar: 'https://i.pravatar.cc/100?img=19', following: 456, likes: 7890, followers: 1890, verified: true, neighborhood: 'Chamisero', bio: 'Psicologa.', address: 'Avenida Chamisero 10700', addressNumber: '10700', addressStreet: 'Avenida Chamisero', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2110, longitude: -70.6610 },
  { id: 14, name: 'Pedro Antonio Ruiz', username: 'pedroruiz', email: 'pedro.ruiz@gmail.com', avatar: 'https://i.pravatar.cc/100?img=20', following: 321, likes: 5432, followers: 876, verified: false, neighborhood: 'Chamisero', bio: 'Mecanico.', address: 'Avenida Chamisero 10750', addressNumber: '10750', addressStreet: 'Avenida Chamisero', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2120, longitude: -70.6620 },
  { id: 15, name: 'Juana del Carmen Soto', username: 'juanasoto', email: 'juana.soto@gmail.com', avatar: 'https://i.pravatar.cc/100?img=21', following: 234, likes: 4567, followers: 1234, verified: false, neighborhood: 'Chamisero', bio: 'Comerciante.', address: 'Calle Los Cerezos 450', addressNumber: '450', addressStreet: 'Calle Los Cerezos', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2130, longitude: -70.6630 },
  { id: 16, name: 'Alberto Enrique Castillo', username: 'albertocastillo', email: 'alberto.castillo@gmail.com', avatar: 'https://i.pravatar.cc/100?img=22', following: 789, likes: 13456, followers: 3123, verified: true, neighborhood: 'Chamisero', bio: 'Constructor.', address: 'Calle Los Aromos 500', addressNumber: '500', addressStreet: 'Calle Los Aromos', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2140, longitude: -70.6640 },
  { id: 17, name: 'Maria Teresa Nunez', username: 'teresanunez', email: 'maria.nunez@gmail.com', avatar: 'https://i.pravatar.cc/100?img=23', following: 567, likes: 8901, followers: 2345, verified: true, neighborhood: 'Chamisero', bio: 'Nutricionista.', address: 'Camino Los Maitenes 550', addressNumber: '550', addressStreet: 'Camino Los Maitenes', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2150, longitude: -70.6650 },
  { id: 18, name: 'Cristobal Andres Moreno', username: 'cristobalmoreno', email: 'cristobal.moreno@gmail.com', avatar: 'https://i.pravatar.cc/100?img=24', following: 432, likes: 6789, followers: 1567, verified: false, neighborhood: 'Chamisero', bio: 'Estudiante.', address: 'Avenida Chamisero 10800', addressNumber: '10800', addressStreet: 'Avenida Chamisero', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2160, longitude: -70.6660 },
  { id: 19, name: 'Elvira Rosa Lopez', username: 'elviralopez', email: 'elvira.lopez@gmail.com', avatar: 'https://i.pravatar.cc/100?img=25', following: 189, likes: 3456, followers: 765, verified: false, neighborhood: 'Chamisero', bio: 'Voluntaria.', address: 'Avenida Chamisero 10850', addressNumber: '10850', addressStreet: 'Avenida Chamisero', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2170, longitude: -70.6670 },
  { id: 20, name: 'Victor Manuel Herrera', username: 'victorherrera', email: 'victor.herrera@gmail.com', avatar: 'https://i.pravatar.cc/100?img=26', following: 678, likes: 11234, followers: 2678, verified: true, neighborhood: 'Chamisero', bio: 'Chef.', address: 'Calle Los Cerezos 600', addressNumber: '600', addressStreet: 'Calle Los Cerezos', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2180, longitude: -70.6680 },
  { id: 21, name: 'Lucia del Pilar Ibanez', username: 'luciaibanez', email: 'lucia.ibanez@gmail.com', avatar: 'https://i.pravatar.cc/100?img=27', following: 543, likes: 8765, followers: 1987, verified: true, neighborhood: 'Chamisero', bio: 'Periodista.', address: 'Calle Los Aromos 650', addressNumber: '650', addressStreet: 'Calle Los Aromos', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2190, longitude: -70.6690 },
  { id: 22, name: 'Andres Felipe Mesa', username: 'andresmesa', email: 'andres.mesa@gmail.com', avatar: 'https://i.pravatar.cc/100?img=28', following: 876, likes: 15678, followers: 3567, verified: true, neighborhood: 'Chamisero', bio: 'Ing. comercial.', address: 'Camino Los Maitenes 700', addressNumber: '700', addressStreet: 'Camino Los Maitenes', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2200, longitude: -70.6700 },
  { id: 23, name: 'Carolina Paz Garcia', username: 'carolinagarcia', email: 'carolina.garcia@gmail.com', avatar: 'https://i.pravatar.cc/100?img=29', following: 654, likes: 12345, followers: 2890, verified: true, neighborhood: 'Chamisero', bio: 'Abogada.', address: 'Avenida Chamisero 10900', addressNumber: '10900', addressStreet: 'Avenida Chamisero', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2210, longitude: -70.6710 },
  { id: 24, name: 'Ricardo Jose Martinez', username: 'ricardomartinez', email: 'ricardo.martinez@gmail.com', avatar: 'https://i.pravatar.cc/100?img=30', following: 432, likes: 7654, followers: 1678, verified: false, neighborhood: 'Chamisero', bio: 'Medico.', address: 'Avenida Chamisero 10950', addressNumber: '10950', addressStreet: 'Avenida Chamisero', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2220, longitude: -70.6720 },
  { id: 25, name: 'Gabriela Ignacia Soto', username: 'gabrielasoto', email: 'gabriela.soto@gmail.com', avatar: 'https://i.pravatar.cc/100?img=31', following: 789, likes: 13456, followers: 3012, verified: true, neighborhood: 'Chamisero', bio: 'Arquitecta.', address: 'Calle Los Cerezos 750', addressNumber: '750', addressStreet: 'Calle Los Cerezos', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2230, longitude: -70.6730 },
  { id: 26, name: 'Fernando Antonio Reyes', username: 'fernandoreyes', email: 'fernando.reyes@gmail.com', avatar: 'https://i.pravatar.cc/100?img=32', following: 567, likes: 9876, followers: 2234, verified: true, neighborhood: 'Chamisero', bio: 'Empresario.', address: 'Calle Los Aromos 800', addressNumber: '800', addressStreet: 'Calle Los Aromos', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2240, longitude: -70.6740 },
  { id: 27, name: 'Valentina Constanza Bravo', username: 'valentinabravo', email: 'valentina.bravo@gmail.com', avatar: 'https://i.pravatar.cc/100?img=33', following: 876, likes: 14567, followers: 3345, verified: true, neighborhood: 'Chamisero', bio: 'Diseñadora.', address: 'Camino Los Maitenes 850', addressNumber: '850', addressStreet: 'Camino Los Maitenes', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2250, longitude: -70.6750 },
  { id: 28, name: 'Marcelo Eduardo Torres', username: 'marceltorres', email: 'marcelo.torres@gmail.com', avatar: 'https://i.pravatar.cc/100?img=34', following: 345, likes: 6543, followers: 1234, verified: false, neighborhood: 'Chamisero', bio: 'Profesor.', address: 'Avenida Chamisero 11000', addressNumber: '11000', addressStreet: 'Avenida Chamisero', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2260, longitude: -70.6760 },
  { id: 29, name: 'Javiera Francisca Lira', username: 'javieralira', email: 'javiera.lira@gmail.com', avatar: 'https://i.pravatar.cc/100?img=35', following: 654, likes: 11234, followers: 2567, verified: true, neighborhood: 'Chamisero', bio: 'Veterinaria.', address: 'Avenida Chamisero 11050', addressNumber: '11050', addressStreet: 'Avenida Chamisero', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2270, longitude: -70.6770 },
  { id: 30, name: 'Sebastian Ignacio Cruz', username: 'sebacruz', email: 'sebastian.cruz@gmail.com', avatar: 'https://i.pravatar.cc/100?img=36', following: 543, likes: 8901, followers: 1987, verified: false, neighborhood: 'Chamisero', bio: 'Ing. sistemas.', address: 'Calle Los Cerezos 900', addressNumber: '900', addressStreet: 'Calle Los Cerezos', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2280, longitude: -70.6780 },
  
  // === 20 USUARIOS EN CHICUREO, COLINA ===
  { id: 31, name: 'Daniela Paz Hernandez', username: 'danielahernandez', email: 'daniela.hernandez@gmail.com', avatar: 'https://i.pravatar.cc/100?img=37', following: 789, likes: 13456, followers: 3012, verified: true, neighborhood: 'Chicureo', bio: 'Contadora.', address: 'Avenida Chicureo 1500', addressNumber: '1500', addressStreet: 'Avenida Chicureo', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2300, longitude: -70.6800 },
  { id: 32, name: 'Rodrigo Andres Fuentes', username: 'rodrigofuentes', email: 'rodrigo.fuentes@gmail.com', avatar: 'https://i.pravatar.cc/100?img=38', following: 432, likes: 7654, followers: 1678, verified: false, neighborhood: 'Chicureo', bio: 'Tecnico.', address: 'Avenida Chicureo 1550', addressNumber: '1550', addressStreet: 'Avenida Chicureo', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2310, longitude: -70.6810 },
  { id: 33, name: 'Cynthia Roxana Pena', username: 'cynthiapena', email: 'cynthia.pena@gmail.com', avatar: 'https://i.pravatar.cc/100?img=39', following: 567, likes: 9876, followers: 2123, verified: true, neighborhood: 'Chicureo', bio: 'Asistente social.', address: 'Calle El Almendro 100', addressNumber: '100', addressStreet: 'Calle El Almendro', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2320, longitude: -70.6820 },
  { id: 34, name: 'Gonzalo Mauricio Vega', username: 'gonzalovega', email: 'gonzalo.vega@gmail.com', avatar: 'https://i.pravatar.cc/100?img=40', following: 654, likes: 12345, followers: 2789, verified: true, neighborhood: 'Chicureo', bio: 'Constructor.', address: 'Calle El Manzano 150', addressNumber: '150', addressStreet: 'Calle El Manzano', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2330, longitude: -70.6830 },
  { id: 35, name: 'Barbara Andrea Jara', username: 'barbarajara', email: 'barbara.jara@gmail.com', avatar: 'https://i.pravatar.cc/100?img=41', following: 876, likes: 15678, followers: 3567, verified: true, neighborhood: 'Chicureo', bio: 'Kinesiologa.', address: 'Camino Los Peumos 200', addressNumber: '200', addressStreet: 'Camino Los Peumos', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2340, longitude: -70.6840 },
  { id: 36, name: 'Walter Renato Diaz', username: 'walterdiaz', email: 'walter.diaz@gmail.com', avatar: 'https://i.pravatar.cc/100?img=42', following: 345, likes: 5678, followers: 1123, verified: false, neighborhood: 'Chicureo', bio: 'Electricista.', address: 'Avenida Chicureo 1600', addressNumber: '1600', addressStreet: 'Avenida Chicureo', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2350, longitude: -70.6850 },
  { id: 37, name: 'Paulina Andrea Mora', username: 'paulinamora', email: 'paulina.mora@gmail.com', avatar: 'https://i.pravatar.cc/100?img=43', following: 543, likes: 8901, followers: 1987, verified: true, neighborhood: 'Chicureo', bio: 'Odontologa.', address: 'Avenida Chicureo 1650', addressNumber: '1650', addressStreet: 'Avenida Chicureo', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2360, longitude: -70.6860 },
  { id: 38, name: 'Christian Eduardo Leal', username: 'christianleal', email: 'christian.leal@gmail.com', avatar: 'https://i.pravatar.cc/100?img=44', following: 678, likes: 11234, followers: 2456, verified: false, neighborhood: 'Chicureo', bio: 'Gasfitero.', address: 'Calle El Almendro 250', addressNumber: '250', addressStreet: 'Calle El Almendro', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2370, longitude: -70.6870 },
  { id: 39, name: 'Monica Jeannette Riquelme', username: 'monicariquelme', email: 'monica.riquelme@gmail.com', avatar: 'https://i.pravatar.cc/100?img=45', following: 432, likes: 7654, followers: 1678, verified: true, neighborhood: 'Chicureo', bio: 'Peluquera.', address: 'Calle El Manzano 300', addressNumber: '300', addressStreet: 'Calle El Manzano', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2380, longitude: -70.6880 },
  { id: 40, name: 'Jorge Luis Campos', username: 'jorgecampos', email: 'jorge.campos@gmail.com', avatar: 'https://i.pravatar.cc/100?img=46', following: 789, likes: 13456, followers: 3012, verified: true, neighborhood: 'Chicureo', bio: 'Pintor.', address: 'Camino Los Peumos 350', addressNumber: '350', addressStreet: 'Camino Los Peumos', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2390, longitude: -70.6890 },
  { id: 41, name: 'Yolanda del Carmen Quiroga', username: 'yolandaquiroga', email: 'yolanda.quiroga@gmail.com', avatar: 'https://i.pravatar.cc/100?img=47', following: 234, likes: 4567, followers: 987, verified: false, neighborhood: 'Chicureo', bio: 'Costurera.', address: 'Avenida Chicureo 1700', addressNumber: '1700', addressStreet: 'Avenida Chicureo', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2400, longitude: -70.6900 },
  { id: 42, name: 'Raul Ernesto Salinas', username: 'raulsalinas', email: 'raul.salinas@gmail.com', avatar: 'https://i.pravatar.cc/100?img=48', following: 567, likes: 9876, followers: 2123, verified: true, neighborhood: 'Chicureo', bio: 'Carpintero.', address: 'Avenida Chicureo 1750', addressNumber: '1750', addressStreet: 'Avenida Chicureo', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2410, longitude: -70.6910 },
  { id: 43, name: 'Susana del Carmen Araya', username: 'susanaraya', email: 'susana.araya@gmail.com', avatar: 'https://i.pravatar.cc/100?img=49', following: 654, likes: 11234, followers: 2456, verified: true, neighborhood: 'Chicureo', bio: 'Panadera.', address: 'Calle El Almendro 400', addressNumber: '400', addressStreet: 'Calle El Almendro', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2420, longitude: -70.6920 },
  { id: 44, name: 'Oscar Manuel Navarro', username: 'oscarnavarro', email: 'oscar.navarro@gmail.com', avatar: 'https://i.pravatar.cc/100?img=50', following: 432, likes: 7654, followers: 1678, verified: false, neighborhood: 'Chicureo', bio: 'Zapatero.', address: 'Calle El Manzano 450', addressNumber: '450', addressStreet: 'Calle El Manzano', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2430, longitude: -70.6930 },
  { id: 45, name: 'Irene Teresa Mendoza', username: 'irenemendoza', email: 'irene.mendoza@gmail.com', avatar: 'https://i.pravatar.cc/100?img=51', following: 876, likes: 14567, followers: 3234, verified: true, neighborhood: 'Chicureo', bio: 'Educadora.', address: 'Camino Los Peumos 500', addressNumber: '500', addressStreet: 'Camino Los Peumos', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2440, longitude: -70.6940 },
  { id: 46, name: 'Tomas Ariel Gonzalez', username: 'tomasgonzalez', email: 'tomas.gonzalez@gmail.com', avatar: 'https://i.pravatar.cc/100?img=52', following: 543, likes: 8901, followers: 1987, verified: false, neighborhood: 'Chicureo', bio: 'Mecanico.', address: 'Avenida Chicureo 1800', addressNumber: '1800', addressStreet: 'Avenida Chicureo', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2450, longitude: -70.6950 },
  { id: 47, name: 'Gladys del Carmen Orellana', username: 'gladysorellana', email: 'gladys.orellana@gmail.com', avatar: 'https://i.pravatar.cc/100?img=53', following: 345, likes: 5678, followers: 1123, verified: false, neighborhood: 'Chicureo', bio: 'Vendedora.', address: 'Avenida Chicureo 1850', addressNumber: '1850', addressStreet: 'Avenida Chicureo', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2460, longitude: -70.6960 },
  { id: 48, name: 'Hector Rene Ponce', username: 'hectorponce', email: 'hector.ponce@gmail.com', avatar: 'https://i.pravatar.cc/100?img=54', following: 678, likes: 11234, followers: 2456, verified: true, neighborhood: 'Chicureo', bio: 'Jardinero.', address: 'Calle El Almendro 550', addressNumber: '550', addressStreet: 'Calle El Almendro', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2470, longitude: -70.6970 },
  { id: 49, name: 'Marisol Andrea Valenzuela', username: 'marisolvalenzuela', email: 'marisol.valenzuela@gmail.com', avatar: 'https://i.pravatar.cc/100?img=55', following: 789, likes: 13456, followers: 3012, verified: true, neighborhood: 'Chicureo', bio: 'Esteticista.', address: 'Calle El Manzano 600', addressNumber: '600', addressStreet: 'Calle El Manzano', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2480, longitude: -70.6980 },
  { id: 50, name: 'Felipe Andres Escobar', username: 'felipeescobar', email: 'felipe.escobar@gmail.com', avatar: 'https://i.pravatar.cc/100?img=56', following: 432, likes: 7654, followers: 1678, verified: false, neighborhood: 'Chicureo', bio: 'Cerrajero.', address: 'Camino Los Peumos 650', addressNumber: '650', addressStreet: 'Camino Los Peumos', city: 'Colina', region: 'Region Metropolitana', latitude: -33.2490, longitude: -70.6990 },
  
  // === 15 USUARIOS EN LAS CONDES ===
  { id: 51, name: 'Veronica del Carmen Lagos', username: 'veronicalagos', email: 'veronica.lagos@gmail.com', avatar: 'https://i.pravatar.cc/100?img=57', following: 654, likes: 11234, followers: 2567, verified: true, neighborhood: 'Las Condes', bio: 'Maestra.', address: 'Avenida Apoquindo 3000', addressNumber: '3000', addressStreet: 'Avenida Apoquindo', city: 'Las Condes', region: 'Region Metropolitana', latitude: -33.4150, longitude: -70.5950 },
  { id: 52, name: 'Manuel Jesus Aravena', username: 'manuelaravena', email: 'manuel.aravena@gmail.com', avatar: 'https://i.pravatar.cc/100?img=58', following: 543, likes: 8901, followers: 1987, verified: false, neighborhood: 'Las Condes', bio: 'Taxista.', address: 'Avenida Apoquindo 3500', addressNumber: '3500', addressStreet: 'Avenida Apoquindo', city: 'Las Condes', region: 'Region Metropolitana', latitude: -33.4180, longitude: -70.5980 },
  { id: 53, name: 'Lidia del Carmen Bustamante', username: 'lidiabustamante', email: 'lidia.bustamante@gmail.com', avatar: 'https://i.pravatar.cc/100?img=59', following: 678, likes: 11234, followers: 2456, verified: true, neighborhood: 'Las Condes', bio: 'Empleada.', address: 'Calle La Piramide 500', addressNumber: '500', addressStreet: 'Calle La Piramide', city: 'Las Condes', region: 'Region Metropolitana', latitude: -33.4200, longitude: -70.6000 },
  { id: 54, name: 'Alex Mauricio Inostroza', username: 'alexinostroza', email: 'alex.inostroza@gmail.com', avatar: 'https://i.pravatar.cc/100?img=60', following: 432, likes: 7654, followers: 1678, verified: false, neighborhood: 'Las Condes', bio: 'Repartidor.', address: 'Calle El Golf 100', addressNumber: '100', addressStreet: 'Calle El Golf', city: 'Las Condes', region: 'Region Metropolitana', latitude: -33.4220, longitude: -70.6020 },
  { id: 55, name: 'Elena del Pilar Cifuentes', username: 'elenacifuentes', email: 'elena.cifuentes@gmail.com', avatar: 'https://i.pravatar.cc/100?img=61', following: 876, likes: 14567, followers: 3234, verified: true, neighborhood: 'Las Condes', bio: 'Farmaceutica.', address: 'Avenida Kennedy 4000', addressNumber: '4000', addressStreet: 'Avenida Kennedy', city: 'Las Condes', region: 'Region Metropolitana', latitude: -33.4250, longitude: -70.6050 },
  { id: 56, name: 'Juan Carlos Retamal', username: 'juanretamal', email: 'juan.retamal@gmail.com', avatar: 'https://i.pravatar.cc/100?img=62', following: 345, likes: 5678, followers: 1123, verified: false, neighborhood: 'Las Condes', bio: 'Conserje.', address: 'Avenida Apoquindo 4000', addressNumber: '4000', addressStreet: 'Avenida Apoquindo', city: 'Las Condes', region: 'Region Metropolitana', latitude: -33.4280, longitude: -70.6080 },
  { id: 57, name: 'Marta Luz Opazo', username: 'martaopazo', email: 'marta.opazo@gmail.com', avatar: 'https://i.pravatar.cc/100?img=63', following: 654, likes: 11234, followers: 2567, verified: true, neighborhood: 'Las Condes', bio: 'Vendedora.', address: 'Avenida Apoquindo 4500', addressNumber: '4500', addressStreet: 'Avenida Apoquindo', city: 'Las Condes', region: 'Region Metropolitana', latitude: -33.4300, longitude: -70.6100 },
  { id: 58, name: 'Diego Andres Ulloa', username: 'diegoulloa', email: 'diego.ulloa@gmail.com', avatar: 'https://i.pravatar.cc/100?img=64', following: 789, likes: 13456, followers: 3012, verified: true, neighborhood: 'Las Condes', bio: 'Guardia.', address: 'Calle La Piramide 800', addressNumber: '800', addressStreet: 'Calle La Piramide', city: 'Las Condes', region: 'Region Metropolitana', latitude: -33.4320, longitude: -70.6120 },
  { id: 59, name: 'Rosa Elvira Santibanez', username: 'rosasantibanez', email: 'rosa.santibanez@gmail.com', avatar: 'https://i.pravatar.cc/100?img=65', following: 234, likes: 4567, followers: 987, verified: false, neighborhood: 'Las Condes', bio: 'Ama llaves.', address: 'Calle El Golf 200', addressNumber: '200', addressStreet: 'Calle El Golf', city: 'Las Condes', region: 'Region Metropolitana', latitude: -33.4350, longitude: -70.6150 },
  { id: 60, name: 'Cristian Marcelo Pena', username: 'cristianpena', email: 'cristian.pena@gmail.com', avatar: 'https://i.pravatar.cc/100?img=66', following: 567, likes: 9876, followers: 2123, verified: true, neighborhood: 'Las Condes', bio: 'Chofer.', address: 'Avenida Kennedy 4500', addressNumber: '4500', addressStreet: 'Avenida Kennedy', city: 'Las Condes', region: 'Region Metropolitana', latitude: -33.4380, longitude: -70.6180 },
  { id: 61, name: 'Nancy del Carmen Gaete', username: 'nancygaete', email: 'nancy.gaete@gmail.com', avatar: 'https://i.pravatar.cc/100?img=67', following: 432, likes: 7654, followers: 1678, verified: false, neighborhood: 'Las Condes', bio: 'Cuidadora.', address: 'Avenida Apoquindo 5000', addressNumber: '5000', addressStreet: 'Avenida Apoquindo', city: 'Las Condes', region: 'Region Metropolitana', latitude: -33.4400, longitude: -70.6200 },
  { id: 62, name: 'Patricio Alejandro Silva', username: 'patosilva', email: 'patricio.silva@gmail.com', avatar: 'https://i.pravatar.cc/100?img=68', following: 876, likes: 14567, followers: 3234, verified: true, neighborhood: 'Las Condes', bio: 'Abogado.', address: 'Avenida Apoquindo 5500', addressNumber: '5500', addressStreet: 'Avenida Apoquindo', city: 'Las Condes', region: 'Region Metropolitana', latitude: -33.4420, longitude: -70.6220 },
  { id: 63, name: 'Marcela Paz Donoso', username: 'marceldonoso', email: 'marcela.donoso@gmail.com', avatar: 'https://i.pravatar.cc/100?img=69', following: 654, likes: 11234, followers: 2567, verified: true, neighborhood: 'Las Condes', bio: 'Traductora.', address: 'Calle La Piramide 1000', addressNumber: '1000', addressStreet: 'Calle La Piramide', city: 'Las Condes', region: 'Region Metropolitana', latitude: -33.4450, longitude: -70.6250 },
  { id: 64, name: 'Leonardo Fabian Fuentes', username: 'leonardofuentes', email: 'leonardo.fuentes@gmail.com', avatar: 'https://i.pravatar.cc/100?img=70', following: 543, likes: 8901, followers: 1987, verified: false, neighborhood: 'Las Condes', bio: 'Fotografo.', address: 'Calle El Golf 300', addressNumber: '300', addressStreet: 'Calle El Golf', city: 'Las Condes', region: 'Region Metropolitana', latitude: -33.4480, longitude: -70.6280 },
  { id: 65, name: 'Sonia Isabel Jaramillo', username: 'soniajaramillo', email: 'sonia.jaramillo@gmail.com', avatar: 'https://i.pravatar.cc/100?img=71', following: 789, likes: 13456, followers: 3012, verified: true, neighborhood: 'Las Condes', bio: 'Terapeuta.', address: 'Avenida Kennedy 5000', addressNumber: '5000', addressStreet: 'Avenida Kennedy', city: 'Las Condes', region: 'Region Metropolitana', latitude: -33.4500, longitude: -70.6300 },
  
  // === 15 USUARIOS EN PROVIDENCIA ===
  { id: 66, name: 'Rodrigo Antonio Ortega', username: 'rodrigoortega', email: 'rodrigo.ortega@gmail.com', avatar: 'https://i.pravatar.cc/100?img=72', following: 345, likes: 5678, followers: 1123, verified: false, neighborhood: 'Providencia', bio: 'Profesor.', address: 'Avenida Providencia 1000', addressNumber: '1000', addressStreet: 'Avenida Providencia', city: 'Providencia', region: 'Region Metropolitana', latitude: -33.4320, longitude: -70.6080 },
  { id: 67, name: 'Claudia Andrea Valdes', username: 'claudiavaldes', email: 'claudia.valdes@gmail.com', avatar: 'https://i.pravatar.cc/100?img=73', following: 678, likes: 11234, followers: 2456, verified: true, neighborhood: 'Providencia', bio: 'Asesora.', address: 'Calle Holanda 500', addressNumber: '500', addressStreet: 'Calle Holanda', city: 'Providencia', region: 'Region Metropolitana', latitude: -33.4350, longitude: -70.6100 },
  { id: 68, name: 'Mauricio Jose Salinas', username: 'mauriciosalinas', email: 'mauricio.salinas@gmail.com', avatar: 'https://i.pravatar.cc/100?img=74', following: 432, likes: 7654, followers: 1678, verified: false, neighborhood: 'Providencia', bio: 'Admin.', address: 'Calle Suecia 200', addressNumber: '200', addressStreet: 'Calle Suecia', city: 'Providencia', region: 'Region Metropolitana', latitude: -33.4380, longitude: -70.6120 },
  { id: 69, name: 'Berta del Carmen Henriquez', username: 'bertahenriquez', email: 'berta.henriquez@gmail.com', avatar: 'https://i.pravatar.cc/100?img=75', following: 654, likes: 11234, followers: 2567, verified: true, neighborhood: 'Providencia', bio: 'Doula.', address: 'Avenida 11 de Septiembre 1500', addressNumber: '1500', addressStreet: 'Avenida 11 de Septiembre', city: 'Providencia', region: 'Region Metropolitana', latitude: -33.4400, longitude: -70.6150 },
  { id: 70, name: 'Alfredo Rene Poblete', username: 'alfredopoblete', email: 'alfredo.poblete@gmail.com', avatar: 'https://i.pravatar.cc/100?img=76', following: 789, likes: 13456, followers: 3012, verified: true, neighborhood: 'Providencia', bio: 'Agronomo.', address: 'Avenida Providencia 1500', addressNumber: '1500', addressStreet: 'Avenida Providencia', city: 'Providencia', region: 'Region Metropolitana', latitude: -33.4420, longitude: -70.6180 },
  { id: 71, name: 'Lorena del Rosario Briceno', username: 'lorenabriceno', email: 'lorena.briceno@gmail.com', avatar: 'https://i.pravatar.cc/100?img=77', following: 234, likes: 4567, followers: 987, verified: false, neighborhood: 'Providencia', bio: 'Maquilladora.', address: 'Avenida Providencia 2000', addressNumber: '2000', addressStreet: 'Avenida Providencia', city: 'Providencia', region: 'Region Metropolitana', latitude: -33.4450, longitude: -70.6200 },
  { id: 72, name: 'Gustavo Adolfo Meza', username: 'gustavomeza', email: 'gustavo.meza@gmail.com', avatar: 'https://i.pravatar.cc/100?img=78', following: 567, likes: 9876, followers: 2123, verified: true, neighborhood: 'Providencia', bio: 'Pastelero.', address: 'Calle Holanda 800', addressNumber: '800', addressStreet: 'Calle Holanda', city: 'Providencia', region: 'Region Metropolitana', latitude: -33.4480, longitude: -70.6220 },
  { id: 73, name: 'Pilar Andrea Saldias', username: 'pilarsaldias', email: 'pilar.saldias@gmail.com', avatar: 'https://i.pravatar.cc/100?img=79', following: 432, likes: 7654, followers: 1678, verified: false, neighborhood: 'Providencia', bio: 'Modista.', address: 'Calle Suecia 400', addressNumber: '400', addressStreet: 'Calle Suecia', city: 'Providencia', region: 'Region Metropolitana', latitude: -33.4500, longitude: -70.6250 },
  { id: 74, name: 'Ernesto Jose Gajardo', username: 'ernestogajardo', email: 'ernesto.gajardo@gmail.com', avatar: 'https://i.pravatar.cc/100?img=80', following: 876, likes: 14567, followers: 3234, verified: true, neighborhood: 'Providencia', bio: 'Abogado.', address: 'Avenida 11 de Septiembre 2000', addressNumber: '2000', addressStreet: 'Avenida 11 de Septiembre', city: 'Providencia', region: 'Region Metropolitana', latitude: -33.4520, longitude: -70.6280 },
  { id: 75, name: 'Ximena del Carmen Pizarro', username: 'ximenapizarro', email: 'ximena.pizarro@gmail.com', avatar: 'https://i.pravatar.cc/100?img=81', following: 654, likes: 11234, followers: 2567, verified: true, neighborhood: 'Providencia', bio: 'Periodista.', address: 'Avenida Providencia 2500', addressNumber: '2500', addressStreet: 'Avenida Providencia', city: 'Providencia', region: 'Region Metropolitana', latitude: -33.4550, longitude: -70.6300 },
  { id: 76, name: 'Juan Francisco Martinez', username: 'juanfcomartinez', email: 'juan.martinez@gmail.com', avatar: 'https://i.pravatar.cc/100?img=82', following: 345, likes: 5678, followers: 1123, verified: false, neighborhood: 'Providencia', bio: 'Barbero.', address: 'Avenida Providencia 3000', addressNumber: '3000', addressStreet: 'Avenida Providencia', city: 'Providencia', region: 'Region Metropolitana', latitude: -33.4580, longitude: -70.6320 },
  { id: 77, name: 'Margarita Rosa Ortega', username: 'margaritaortega', email: 'margarita.ortega@gmail.com', avatar: 'https://i.pravatar.cc/100?img=83', following: 678, likes: 11234, followers: 2456, verified: true, neighborhood: 'Providencia', bio: 'Decoradora.', address: 'Calle Holanda 1000', addressNumber: '1000', addressStreet: 'Calle Holanda', city: 'Providencia', region: 'Region Metropolitana', latitude: -33.4600, longitude: -70.6350 },
  { id: 78, name: 'Victor Hugo Lopez', username: 'victorlopez', email: 'victor.lopez@gmail.com', avatar: 'https://i.pravatar.cc/100?img=84', following: 543, likes: 8901, followers: 1987, verified: false, neighborhood: 'Providencia', bio: 'Musico.', address: 'Calle Suecia 600', addressNumber: '600', addressStreet: 'Calle Suecia', city: 'Providencia', region: 'Region Metropolitana', latitude: -33.4620, longitude: -70.6380 },
  { id: 79, name: 'Rosario del Carmen Vera', username: 'rosariovera', email: 'rosario.vera@gmail.com', avatar: 'https://i.pravatar.cc/100?img=85', following: 789, likes: 13456, followers: 3012, verified: true, neighborhood: 'Providencia', bio: 'Abogada.', address: 'Avenida 11 de Septiembre 2500', addressNumber: '2500', addressStreet: 'Avenida 11 de Septiembre', city: 'Providencia', region: 'Region Metropolitana', latitude: -33.4650, longitude: -70.6400 },
  { id: 80, name: 'Sergio Antonio Delgado', username: 'sergodelgado', email: 'sergio.delgado@gmail.com', avatar: 'https://i.pravatar.cc/100?img=86', following: 234, likes: 4567, followers: 987, verified: false, neighborhood: 'Providencia', bio: 'Carpintero.', address: 'Avenida Providencia 3500', addressNumber: '3500', addressStreet: 'Avenida Providencia', city: 'Providencia', region: 'Region Metropolitana', latitude: -33.4680, longitude: -70.6420 },
  
  // === 10 USUARIOS EN VINA DEL MAR ===
  { id: 81, name: 'Luz Maria Ibacache', username: 'luzibacache', email: 'luz.ibacache@gmail.com', avatar: 'https://i.pravatar.cc/100?img=87', following: 567, likes: 9876, followers: 2123, verified: true, neighborhood: 'Vina del Mar', bio: 'Enfermera.', address: 'Avenida San Martin 200', addressNumber: '200', addressStreet: 'Avenida San Martin', city: 'Vina del Mar', region: 'Region de Valparaiso', latitude: -33.0170, longitude: -71.5520 },
  { id: 82, name: 'Pedro Pablo Henriquez', username: 'pedrohenriquez', email: 'pedro.henriquez@gmail.com', avatar: 'https://i.pravatar.cc/100?img=88', following: 654, likes: 11234, followers: 2567, verified: true, neighborhood: 'Vina del Mar', bio: 'Ing. electrico.', address: 'Avenida Libertad 500', addressNumber: '500', addressStreet: 'Avenida Libertad', city: 'Vina del Mar', region: 'Region de Valparaiso', latitude: -33.0200, longitude: -71.5550 },
  { id: 83, name: 'Ileana del Valle Morales', username: 'ileanamorales', email: 'ileana.morales@gmail.com', avatar: 'https://i.pravatar.cc/100?img=89', following: 432, likes: 7654, followers: 1678, verified: false, neighborhood: 'Vina del Mar', bio: 'Diseñadora.', address: 'Calle Valparaiso 100', addressNumber: '100', addressStreet: 'Calle Valparaiso', city: 'Vina del Mar', region: 'Region de Valparaiso', latitude: -33.0230, longitude: -71.5580 },
  { id: 84, name: 'Miguel Angel Quijada', username: 'miguelquijada', email: 'miguel.quijada@gmail.com', avatar: 'https://i.pravatar.cc/100?img=90', following: 876, likes: 14567, followers: 3234, verified: true, neighborhood: 'Vina del Mar', bio: 'Mecanico.', address: 'Avenida 1 Norte 300', addressNumber: '300', addressStreet: 'Avenida 1 Norte', city: 'Vina del Mar', region: 'Region de Valparaiso', latitude: -33.0260, longitude: -71.5600 },
  { id: 85, name: 'Gloria del Carmen Soto', username: 'gloriasoto', email: 'gloria.soto@gmail.com', avatar: 'https://i.pravatar.cc/100?img=91', following: 654, likes: 11234, followers: 2567, verified: true, neighborhood: 'Vina del Mar', bio: 'Secretaria.', address: 'Avenida San Martin 400', addressNumber: '400', addressStreet: 'Avenida San Martin', city: 'Vina del Mar', region: 'Region de Valparaiso', latitude: -33.0290, longitude: -71.5630 },
  { id: 86, name: 'Francisco Jose Aviles', username: 'franciscoaviles', email: 'francisco.aviles@gmail.com', avatar: 'https://i.pravatar.cc/100?img=92', following: 345, likes: 5678, followers: 1123, verified: false, neighborhood: 'Vina del Mar', bio: 'Plomero.', address: 'Avenida Libertad 700', addressNumber: '700', addressStreet: 'Avenida Libertad', city: 'Vina del Mar', region: 'Region de Valparaiso', latitude: -33.0320, longitude: -71.5660 },
  { id: 87, name: 'Teresa de Jesus Navarrete', username: 'teresanavarrete', email: 'teresa.navarrete@gmail.com', avatar: 'https://i.pravatar.cc/100?img=93', following: 678, likes: 11234, followers: 2456, verified: true, neighborhood: 'Vina del Mar', bio: 'Cuidadora.', address: 'Calle Valparaiso 200', addressNumber: '200', addressStreet: 'Calle Valparaiso', city: 'Vina del Mar', region: 'Region de Valparaiso', latitude: -33.0350, longitude: -71.5690 },
  { id: 88, name: 'Jorge Eduardo Pizarro', username: 'jorgepizarro', email: 'jorge.pizarro@gmail.com', avatar: 'https://i.pravatar.cc/100?img=94', following: 543, likes: 8901, followers: 1987, verified: false, neighborhood: 'Vina del Mar', bio: 'Herrero.', address: 'Avenida 1 Norte 500', addressNumber: '500', addressStreet: 'Avenida 1 Norte', city: 'Vina del Mar', region: 'Region de Valparaiso', latitude: -33.0380, longitude: -71.5720 },
  { id: 89, name: 'Blanca Estela Retamal', username: 'blancaretamal', email: 'blanca.retamal@gmail.com', avatar: 'https://i.pravatar.cc/100?img=95', following: 789, likes: 13456, followers: 3012, verified: true, neighborhood: 'Vina del Mar', bio: 'Chef.', address: 'Avenida San Martin 600', addressNumber: '600', addressStreet: 'Avenida San Martin', city: 'Vina del Mar', region: 'Region de Valparaiso', latitude: -33.0410, longitude: -71.5750 },
  { id: 90, name: 'Rene Osvaldo Olivares', username: 'reneolivares', email: 'rene.olivares@gmail.com', avatar: 'https://i.pravatar.cc/100?img=96', following: 234, likes: 4567, followers: 987, verified: false, neighborhood: 'Vina del Mar', bio: 'Vendedor.', address: 'Avenida Libertad 900', addressNumber: '900', addressStreet: 'Avenida Libertad', city: 'Vina del Mar', region: 'Region de Valparaiso', latitude: -33.0440, longitude: -71.5780 },
  
  // === 10 USUARIOS EN MACUL ===
  { id: 91, name: 'Amanda del Carmen Cubillos', username: 'amandacubillos', email: 'amanda.cubillos@gmail.com', avatar: 'https://i.pravatar.cc/100?img=97', following: 567, likes: 9876, followers: 2123, verified: true, neighborhood: 'Macul', bio: 'Masajista.', address: 'Avenida Grecia 1000', addressNumber: '1000', addressStreet: 'Avenida Grecia', city: 'Macul', region: 'Region Metropolitana', latitude: -33.4800, longitude: -70.6000 },
  { id: 92, name: 'Juan Carlos Abarca', username: 'juanabarca', email: 'juan.abarca@gmail.com', avatar: 'https://i.pravatar.cc/100?img=98', following: 432, likes: 7654, followers: 1678, verified: true, neighborhood: 'Macul', bio: 'Agricultor.', address: 'Avenida Departamental 500', addressNumber: '500', addressStreet: 'Avenida Departamental', city: 'Macul', region: 'Region Metropolitana', latitude: -33.4830, longitude: -70.6030 },
  { id: 93, name: 'Maria Antonieta Concha', username: 'maconcha', email: 'maria.concha@gmail.com', avatar: 'https://i.pravatar.cc/100?img=99', following: 654, likes: 11234, followers: 2567, verified: true, neighborhood: 'Macul', bio: 'Artesana.', address: 'Calle Las Torres 200', addressNumber: '200', addressStreet: 'Calle Las Torres', city: 'Macul', region: 'Region Metropolitana', latitude: -33.4860, longitude: -70.6060 },
  { id: 94, name: 'Luis Hernan Cortes', username: 'luiscortes', email: 'luis.cortes@gmail.com', avatar: 'https://i.pravatar.cc/100?img=100', following: 876, likes: 14567, followers: 3234, verified: true, neighborhood: 'Macul', bio: 'Pescador.', address: 'Calle El Peral 300', addressNumber: '300', addressStreet: 'Calle El Peral', city: 'Macul', region: 'Region Metropolitana', latitude: -33.4890, longitude: -70.6090 },
  { id: 95, name: 'Elvira del Pilar Acuna', username: 'elviraacuna', email: 'elvira.acuna@gmail.com', avatar: 'https://i.pravatar.cc/100?img=101', following: 345, likes: 5678, followers: 1123, verified: false, neighborhood: 'Macul', bio: 'Turismo.', address: 'Avenida Grecia 1500', addressNumber: '1500', addressStreet: 'Avenida Grecia', city: 'Macul', region: 'Region Metropolitana', latitude: -33.4920, longitude: -70.6120 },
  { id: 96, name: 'Carlos Alberto Farias', username: 'carlosfarias', email: 'carlos.farias@gmail.com', avatar: 'https://i.pravatar.cc/100?img=102', following: 678, likes: 11234, followers: 2456, verified: true, neighborhood: 'Macul', bio: 'Minero.', address: 'Avenida Departamental 800', addressNumber: '800', addressStreet: 'Avenida Departamental', city: 'Macul', region: 'Region Metropolitana', latitude: -33.4950, longitude: -70.6150 },
  { id: 97, name: 'Rosa del Carmen Jelves', username: 'rosajelves', email: 'rosa.jelves@gmail.com', avatar: 'https://i.pravatar.cc/100?img=103', following: 543, likes: 8901, followers: 1987, verified: false, neighborhood: 'Macul', bio: 'Comerciante.', address: 'Calle Las Torres 400', addressNumber: '400', addressStreet: 'Calle Las Torres', city: 'Macul', region: 'Region Metropolitana', latitude: -33.4980, longitude: -70.6180 },
  { id: 98, name: 'Roberto Carlos Yanez', username: 'robertoyaniez', email: 'roberto.yanez@gmail.com', avatar: 'https://i.pravatar.cc/100?img=104', following: 789, likes: 13456, followers: 3012, verified: true, neighborhood: 'Macul', bio: 'Ganadero.', address: 'Calle El Peral 500', addressNumber: '500', addressStreet: 'Calle El Peral', city: 'Macul', region: 'Region Metropolitana', latitude: -33.5010, longitude: -70.6210 },
  { id: 99, name: 'Marta Lucia Pinochet', username: 'martapinochet', email: 'marta.pinochet@gmail.com', avatar: 'https://i.pravatar.cc/100?img=105', following: 234, likes: 4567, followers: 987, verified: false, neighborhood: 'Macul', bio: 'Turismo.', address: 'Avenida Grecia 2000', addressNumber: '2000', addressStreet: 'Avenida Grecia', city: 'Macul', region: 'Region Metropolitana', latitude: -33.5040, longitude: -70.6240 },
  { id: 100, name: 'Jorge Antonio Monsalve', username: 'jorgemonsalve', email: 'jorge.monsalve@gmail.com', avatar: 'https://i.pravatar.cc/100?img=106', following: 567, likes: 9876, followers: 2123, verified: true, neighborhood: 'Macul', bio: 'Agronomo.', address: 'Avenida Departamental 1000', addressNumber: '1000', addressStreet: 'Avenida Departamental', city: 'Macul', region: 'Region Metropolitana', latitude: -33.5070, longitude: -70.6270 },
];

const AppInitializer = () => {
  useEffect(() => {
    // Always overwrite with fresh data to ensure updates
    localStorage.setItem('friendbook_users', JSON.stringify(demoUsers));
    console.log('AppInitializer: Users data refreshed with new coordinates');

    // Auto-login with first user if not already logged in
    const currentUser = localStorage.getItem('friendbook_current_user');
    const session = localStorage.getItem('friendbook_session');
    
    if (!currentUser || !session) {
      const defaultUser = {
        ...demoUsers[0],
        status: 'active',
        lastLogin: new Date().toISOString()
      };
      localStorage.setItem('friendbook_current_user', JSON.stringify(defaultUser));
      
      // Create session
      const sessionData = {
        createdAt: Date.now(),
        userId: defaultUser.id
      };
      localStorage.setItem('friendbook_session', JSON.stringify(sessionData));
      
      console.log('✅ AppInitializer: Auto-logged in as', defaultUser.name);
    }
  }, []);

  return null;
};

export default AppInitializer;